### ISSUE TITLE
Download with mass renaming

### ISSUE THREAD

**Issue by dinogon** [PactInteractive/image-downloader#50]
I suggest that we can add some functions to this extension:

1. Add padding to rename function.
2. Naming file should follow the index of webview
3. Having download destination would be better

By the way, thank for the good images dowloader ^.^

**Comment by 3xploiton3** [comment]
its would be great if we can bulk rename

**Comment by team3star** [comment]
Can I use "YYYY/MM/DD" etc?

**Comment by vdsabev** [comment]
The upcoming 3.0 release addresses some of the issues originally described here:
1. I've added padding so that if you're downloading 13 images they'll be numbered as 01, 02, 03 etc.
2. The numbering order will match the order of the images that you see in the popup
3. Not sure what "download destination" means

As to using patterns like `YYYY-MM-DD` I'm adding this as a feature request and will consider working on it in the future.
